// This file is auto-generated by @hey-api/openapi-ts

export const ADIPublicSchema = {
    properties: {
        patient_deiden_id: {
            type: 'string',
            title: 'Patient Deiden Id'
        },
        encounter_deiden_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Encounter Deiden Id'
        },
        deid_contact_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Deid Contact Date'
        },
        adi_national_rank: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Adi National Rank'
        }
    },
    type: 'object',
    required: ['patient_deiden_id', 'encounter_deiden_id', 'deid_contact_date', 'adi_national_rank'],
    title: 'ADIPublic'
} as const;

export const BPPublicSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        patient_deiden_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Patient Deiden Id'
        },
        encounter_deiden_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Encounter Deiden Id'
        },
        deid_bp_measurement_datetime: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Deid Bp Measurement Datetime'
        },
        systolic: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Systolic'
        },
        diastolic: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Diastolic'
        }
    },
    type: 'object',
    required: ['id', 'patient_deiden_id', 'encounter_deiden_id', 'deid_bp_measurement_datetime', 'systolic', 'diastolic'],
    title: 'BPPublic'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const CKDDataPublicSchema = {
    properties: {
        patient_deiden_id: {
            type: 'string',
            title: 'Patient Deiden Id'
        },
        encounter_deiden_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Encounter Deiden Id'
        },
        deid_diagnosis_start_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Deid Diagnosis Start Date'
        },
        diagnosis_code: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Diagnosis Code'
        },
        diagnosis_description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Diagnosis Description'
        }
    },
    type: 'object',
    required: ['patient_deiden_id', 'encounter_deiden_id', 'deid_diagnosis_start_date', 'diagnosis_code', 'diagnosis_description'],
    title: 'CKDDataPublic'
} as const;

export const ConditionOccurrencePublicSchema = {
    properties: {
        person_id: {
            type: 'integer',
            title: 'Person Id'
        },
        condition_concept_id: {
            type: 'integer',
            title: 'Condition Concept Id'
        },
        condition_start_date: {
            type: 'string',
            format: 'date',
            title: 'Condition Start Date'
        },
        condition_start_datetime: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Condition Start Datetime'
        },
        condition_end_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Condition End Date'
        },
        condition_end_datetime: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Condition End Datetime'
        },
        condition_type_concept_id: {
            type: 'integer',
            title: 'Condition Type Concept Id'
        },
        condition_status_concept_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Condition Status Concept Id'
        },
        stop_reason: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Stop Reason'
        },
        provider_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Provider Id'
        },
        visit_occurrence_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Visit Occurrence Id'
        },
        condition_source_value: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Condition Source Value'
        },
        condition_source_concept_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Condition Source Concept Id'
        },
        condition_status_source_value: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Condition Status Source Value'
        },
        condition_occurrence_id: {
            type: 'integer',
            title: 'Condition Occurrence Id'
        }
    },
    type: 'object',
    required: ['person_id', 'condition_concept_id', 'condition_start_date', 'condition_type_concept_id', 'condition_occurrence_id'],
    title: 'ConditionOccurrencePublic'
} as const;

export const DemographicsPublicSchema = {
    properties: {
        patient_deiden_id: {
            type: 'string',
            title: 'Patient Deiden Id'
        },
        deid_date_of_birth: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Deid Date Of Birth'
        },
        sex: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sex'
        },
        race: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Race'
        },
        ethnicity: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ethnicity'
        }
    },
    type: 'object',
    required: ['patient_deiden_id', 'deid_date_of_birth', 'sex', 'race', 'ethnicity'],
    title: 'DemographicsPublic'
} as const;

export const FullPatientProfileSchema = {
    properties: {
        patient: {
            '$ref': '#/components/schemas/PatientPublic'
        },
        visit_info: {
            '$ref': '#/components/schemas/VisitInfo'
        },
        demographics: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/DemographicsPublic'
                },
                {
                    type: 'null'
                }
            ]
        },
        bp_records: {
            items: {
                '$ref': '#/components/schemas/BPPublic'
            },
            type: 'array',
            title: 'Bp Records',
            default: []
        },
        adi_records: {
            items: {
                '$ref': '#/components/schemas/ADIPublic'
            },
            type: 'array',
            title: 'Adi Records',
            default: []
        },
        lab_records: {
            items: {
                '$ref': '#/components/schemas/LabsPublic'
            },
            type: 'array',
            title: 'Lab Records',
            default: []
        },
        ckd_data_records: {
            items: {
                '$ref': '#/components/schemas/CKDDataPublic'
            },
            type: 'array',
            title: 'Ckd Data Records',
            default: []
        }
    },
    type: 'object',
    required: ['patient'],
    title: 'FullPatientProfile',
    description: 'Complete patient profile with all related data.'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const ItemCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'ItemCreate'
} as const;

export const ItemPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['title', 'id', 'owner_id'],
    title: 'ItemPublic'
} as const;

export const ItemUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'ItemUpdate'
} as const;

export const ItemsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ItemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ItemsPublic'
} as const;

export const LabsPublicSchema = {
    properties: {
        patient_deiden_id: {
            type: 'string',
            title: 'Patient Deiden Id'
        },
        encounter_deiden_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Encounter Deiden Id'
        },
        lab_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Lab Name'
        },
        loinc_code: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Loinc Code'
        },
        deid_inferred_specimen_datetime: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Deid Inferred Specimen Datetime'
        },
        lab_result: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Lab Result'
        },
        lab_unit: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Lab Unit'
        }
    },
    type: 'object',
    required: ['patient_deiden_id', 'encounter_deiden_id', 'lab_name', 'loinc_code', 'deid_inferred_specimen_datetime', 'lab_result', 'lab_unit'],
    title: 'LabsPublic'
} as const;

export const MeasurementPublicSchema = {
    properties: {
        person_id: {
            type: 'integer',
            title: 'Person Id'
        },
        measurement_concept_id: {
            type: 'integer',
            title: 'Measurement Concept Id'
        },
        measurement_date: {
            type: 'string',
            format: 'date',
            title: 'Measurement Date'
        },
        measurement_datetime: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Measurement Datetime'
        },
        measurement_time: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 10
                },
                {
                    type: 'null'
                }
            ],
            title: 'Measurement Time'
        },
        measurement_type_concept_id: {
            type: 'integer',
            title: 'Measurement Type Concept Id'
        },
        operator_concept_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Operator Concept Id'
        },
        value_as_number: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Value As Number'
        },
        value_as_concept_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Value As Concept Id'
        },
        unit_concept_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Unit Concept Id'
        },
        range_low: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Range Low'
        },
        range_high: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Range High'
        },
        provider_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Provider Id'
        },
        visit_occurrence_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Visit Occurrence Id'
        },
        measurement_source_value: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Measurement Source Value'
        },
        measurement_source_concept_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Measurement Source Concept Id'
        },
        unit_source_value: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Unit Source Value'
        },
        unit_source_concept_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Unit Source Concept Id'
        },
        value_source_value: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Value Source Value'
        },
        measurement_id: {
            type: 'integer',
            title: 'Measurement Id'
        }
    },
    type: 'object',
    required: ['person_id', 'measurement_concept_id', 'measurement_date', 'measurement_type_concept_id', 'measurement_id'],
    title: 'MeasurementPublic'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const PatientPublicSchema = {
    properties: {
        patient_deiden_id: {
            type: 'string',
            maxLength: 255,
            title: 'Patient Deiden Id'
        },
        date_of_birth: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Date Of Birth'
        },
        sex: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 10
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sex'
        },
        race: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Race'
        },
        ethnicity: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ethnicity'
        },
        id: {
            type: 'string',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['patient_deiden_id', 'id'],
    title: 'PatientPublic'
} as const;

export const PatientsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/PatientPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'PatientsPublic'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;

export const VisitInfoSchema = {
    properties: {
        number_of_visits: {
            type: 'integer',
            title: 'Number Of Visits',
            default: 0
        },
        number_of_encounters: {
            type: 'integer',
            title: 'Number Of Encounters',
            default: 0
        },
        first_visit_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'First Visit Date'
        },
        last_visit_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Visit Date'
        },
        tracking_period_days: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tracking Period Days'
        }
    },
    type: 'object',
    title: 'VisitInfo',
    description: 'Visit information aggregated from patient encounters.'
} as const;

export const VisitOccurrencePublicSchema = {
    properties: {
        person_id: {
            type: 'integer',
            title: 'Person Id'
        },
        visit_concept_id: {
            type: 'integer',
            title: 'Visit Concept Id'
        },
        visit_start_date: {
            type: 'string',
            format: 'date',
            title: 'Visit Start Date'
        },
        visit_start_datetime: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Visit Start Datetime'
        },
        visit_end_date: {
            type: 'string',
            format: 'date',
            title: 'Visit End Date'
        },
        visit_end_datetime: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Visit End Datetime'
        },
        visit_type_concept_id: {
            type: 'integer',
            title: 'Visit Type Concept Id'
        },
        provider_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Provider Id'
        },
        care_site_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Care Site Id'
        },
        visit_source_value: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Visit Source Value'
        },
        visit_source_concept_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Visit Source Concept Id'
        },
        admitted_from_concept_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Admitted From Concept Id'
        },
        admitted_from_source_value: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Admitted From Source Value'
        },
        discharged_to_concept_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Discharged To Concept Id'
        },
        discharged_to_source_value: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Discharged To Source Value'
        },
        preceding_visit_occurrence_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Preceding Visit Occurrence Id'
        },
        visit_occurrence_id: {
            type: 'integer',
            title: 'Visit Occurrence Id'
        }
    },
    type: 'object',
    required: ['person_id', 'visit_concept_id', 'visit_start_date', 'visit_end_date', 'visit_type_concept_id', 'visit_occurrence_id'],
    title: 'VisitOccurrencePublic'
} as const;