// This file is auto-generated by @hey-api/openapi-ts

export type ADIPublic = {
    patient_deiden_id: string;
    encounter_deiden_id: (string | null);
    deid_contact_date: (string | null);
    adi_national_rank: (string | null);
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type BPPublic = {
    id: number;
    patient_deiden_id: (string | null);
    encounter_deiden_id: (string | null);
    deid_bp_measurement_datetime: (string | null);
    systolic: (number | null);
    diastolic: (number | null);
};

export type CKDDataPublic = {
    patient_deiden_id: string;
    encounter_deiden_id: (string | null);
    deid_diagnosis_start_date: (string | null);
    diagnosis_code: (string | null);
    diagnosis_description: (string | null);
};

export type ConditionOccurrencePublic = {
    person_id: number;
    condition_concept_id: number;
    condition_start_date: string;
    condition_start_datetime?: (string | null);
    condition_end_date?: (string | null);
    condition_end_datetime?: (string | null);
    condition_type_concept_id: number;
    condition_status_concept_id?: (number | null);
    stop_reason?: (string | null);
    provider_id?: (number | null);
    visit_occurrence_id?: (number | null);
    condition_source_value?: (string | null);
    condition_source_concept_id?: (number | null);
    condition_status_source_value?: (string | null);
    condition_occurrence_id: number;
};

export type DemographicsPublic = {
    patient_deiden_id: string;
    deid_date_of_birth: (string | null);
    sex: (string | null);
    race: (string | null);
    ethnicity: (string | null);
};

/**
 * Complete patient profile with all related data.
 */
export type FullPatientProfile = {
    patient: PatientPublic;
    visit_info?: VisitInfo;
    demographics?: (DemographicsPublic | null);
    bp_records?: Array<BPPublic>;
    adi_records?: Array<ADIPublic>;
    lab_records?: Array<LabsPublic>;
    ckd_data_records?: Array<CKDDataPublic>;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type LabsPublic = {
    patient_deiden_id: string;
    encounter_deiden_id: (string | null);
    lab_name: (string | null);
    loinc_code: (string | null);
    deid_inferred_specimen_datetime: (string | null);
    lab_result: (string | null);
    lab_unit: (string | null);
};

export type MeasurementPublic = {
    person_id: number;
    measurement_concept_id: number;
    measurement_date: string;
    measurement_datetime?: (string | null);
    measurement_time?: (string | null);
    measurement_type_concept_id: number;
    operator_concept_id?: (number | null);
    value_as_number?: (number | null);
    value_as_concept_id?: (number | null);
    unit_concept_id?: (number | null);
    range_low?: (number | null);
    range_high?: (number | null);
    provider_id?: (number | null);
    visit_occurrence_id?: (number | null);
    measurement_source_value?: (string | null);
    measurement_source_concept_id?: (number | null);
    unit_source_value?: (string | null);
    unit_source_concept_id?: (number | null);
    value_source_value?: (string | null);
    measurement_id: number;
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PatientPublic = {
    patient_deiden_id: string;
    date_of_birth?: (string | null);
    sex?: (string | null);
    race?: (string | null);
    ethnicity?: (string | null);
    id: string;
};

export type PatientsPublic = {
    data: Array<PatientPublic>;
    count: number;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

/**
 * Visit information aggregated from patient encounters.
 */
export type VisitInfo = {
    number_of_visits?: number;
    number_of_encounters?: number;
    first_visit_date?: (string | null);
    last_visit_date?: (string | null);
    tracking_period_days?: (number | null);
};

export type VisitOccurrencePublic = {
    person_id: number;
    visit_concept_id: number;
    visit_start_date: string;
    visit_start_datetime?: (string | null);
    visit_end_date: string;
    visit_end_datetime?: (string | null);
    visit_type_concept_id: number;
    provider_id?: (number | null);
    care_site_id?: (number | null);
    visit_source_value?: (string | null);
    visit_source_concept_id?: (number | null);
    admitted_from_concept_id?: (number | null);
    admitted_from_source_value?: (string | null);
    discharged_to_concept_id?: (number | null);
    discharged_to_source_value?: (string | null);
    preceding_visit_occurrence_id?: (number | null);
    visit_occurrence_id: number;
};

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type OmopGetPersonData = {
    personId: number;
};

export type OmopGetPersonResponse = (unknown);

export type OmopListPersonsData = {
    limit?: number;
    /**
     * Search by person ID or source values
     */
    q?: (string | null);
    skip?: number;
};

export type OmopListPersonsResponse = (unknown);

export type OmopGetPersonConditionsData = {
    limit?: number;
    personId: number;
    skip?: number;
};

export type OmopGetPersonConditionsResponse = (unknown);

export type OmopGetConditionData = {
    conditionId: number;
};

export type OmopGetConditionResponse = (ConditionOccurrencePublic);

export type OmopGetPersonMeasurementsData = {
    limit?: number;
    personId: number;
    skip?: number;
};

export type OmopGetPersonMeasurementsResponse = (unknown);

export type OmopGetMeasurementData = {
    measurementId: number;
};

export type OmopGetMeasurementResponse = (MeasurementPublic);

export type OmopGetMeasurementsByConceptData = {
    conceptId: number;
    endDate?: (string | null);
    limit?: number;
    skip?: number;
    startDate?: (string | null);
};

export type OmopGetMeasurementsByConceptResponse = (unknown);

export type OmopGetPersonMedicationsData = {
    limit?: number;
    personId: number;
    skip?: number;
};

export type OmopGetPersonMedicationsResponse = (unknown);

export type OmopGetActiveMedicationsData = {
    personId: number;
};

export type OmopGetActiveMedicationsResponse = (unknown);

export type OmopGetPersonVisitsData = {
    limit?: number;
    personId: number;
    skip?: number;
};

export type OmopGetPersonVisitsResponse = (unknown);

export type OmopGetVisitData = {
    visitId: number;
};

export type OmopGetVisitResponse = (VisitOccurrencePublic);

export type OmopGetPersonObservationsData = {
    limit?: number;
    personId: number;
    skip?: number;
};

export type OmopGetPersonObservationsResponse = (unknown);

export type OmopGetPersonProceduresData = {
    limit?: number;
    personId: number;
    skip?: number;
};

export type OmopGetPersonProceduresResponse = (unknown);

export type OmopSearchConceptsData = {
    limit?: number;
    q: string;
    skip?: number;
};

export type OmopSearchConceptsResponse = (unknown);

export type OmopGetConceptsByDomainData = {
    domainId: string;
    limit?: number;
    skip?: number;
};

export type OmopGetConceptsByDomainResponse = (unknown);

export type OmopGetConceptData = {
    conceptId: number;
};

export type OmopGetConceptResponse = (unknown);

export type PatientsReadPatientsData = {
    limit?: number;
    skip?: number;
};

export type PatientsReadPatientsResponse = (PatientsPublic);

export type PatientsReadPatientByUuidData = {
    patientUuid: string;
};

export type PatientsReadPatientByUuidResponse = (FullPatientProfile);

export type PatientsReadPatientData = {
    patientId: string;
};

export type PatientsReadPatientResponse = (FullPatientProfile);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);